/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import ActionEffectLayer from "./script/game/ActionEffectLayer"
import ActionMenu from "./script/game/ActionMenu"
import DiceLayer from "./script/game/DiceLayer"
import EatOptionLayer from "./script/game/EatOptionLayer"
import GameUI from "./script/GameUI"
import GameController from "./script/GameController"
import JokerScript from "./script/game/tile/JokerScript"
import TimePointLayer from "./script/game/TimePointLayer"
import ShowOutLayer from "./script/game/ShowOutLayer"
import TileLayerSelf from "./script/game/tileLayer/TileLayerSelf"
import FlowerList from "./script/game/tileLayer/FlowerList"
import OutList from "./script/game/tileLayer/OutList"
import SelfTileTouchScript from "./script/game/tile/SelfTileTouchScript"
import EatList from "./script/game/tileLayer/EatList"
import TileLayer from "./script/game/tileLayer/TileLayer"
import IndexUI from "./script/IndexUI"
import FullScreen from "./FullScreen"
import ResultDialogUI from "./script/popup/ResultDialogUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1920;
    static height:number=1080;
    static scaleMode:string="fixedauto";
    static screenMode:string="horizontal";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="index/Index.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/game/ActionEffectLayer.ts",ActionEffectLayer);
        reg("script/game/ActionMenu.ts",ActionMenu);
        reg("script/game/DiceLayer.ts",DiceLayer);
        reg("script/game/EatOptionLayer.ts",EatOptionLayer);
        reg("script/GameUI.ts",GameUI);
        reg("script/GameController.ts",GameController);
        reg("script/game/tile/JokerScript.ts",JokerScript);
        reg("script/game/TimePointLayer.ts",TimePointLayer);
        reg("script/game/ShowOutLayer.ts",ShowOutLayer);
        reg("script/game/tileLayer/TileLayerSelf.ts",TileLayerSelf);
        reg("script/game/tileLayer/FlowerList.ts",FlowerList);
        reg("script/game/tileLayer/OutList.ts",OutList);
        reg("script/game/tile/SelfTileTouchScript.ts",SelfTileTouchScript);
        reg("script/game/tileLayer/EatList.ts",EatList);
        reg("script/game/tileLayer/TileLayer.ts",TileLayer);
        reg("script/IndexUI.ts",IndexUI);
        reg("FullScreen.ts",FullScreen);
        reg("script/popup/ResultDialogUI.ts",ResultDialogUI);
    }
}
GameConfig.init();